### ISSUE TITLE
执行 npm run dev失败

### ISSUE THREAD

**Issue by gocpplua** [yuyuanshifu/minio-breakpoint-upload#35]
npm run dev

> minio@1.0.0 dev /data/chenqi/minio-breakpoint-upload/web_src/minio
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'webpack'
Require stack:
- /data/chenqi/minio-breakpoint-upload/web_src/minio/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/data/chenqi/minio-breakpoint-upload/web_src/minio/node_modules/webpack-dev-server/bin/webpack-dev-server.js:12:17)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/chenqi/minio-breakpoint-upload/web_src/minio/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! minio@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minio@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/SENSETIME/chenqi1/.npm/_logs/2022-07-13T02_57_01_662Z-debug.log

**Comment by gocpplua** [comment]
> npm run dev
> 
> > minio@1.0.0 dev /data/chenqi/minio-breakpoint-upload/web_src/minio
> > webpack-dev-server --inline --progress --config build/webpack.dev.conf.js
> 
> internal/modules/cjs/loader.js:888 throw err; ^
> 
> Error: Cannot find module 'webpack' Require stack:
> 
> * /data/chenqi/minio-breakpoint-upload/web_src/minio/node_modules/webpack-dev-server/bin/webpack-dev-server.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:730:27)
>   at Module.require (internal/modules/cjs/loader.js:957:19)
>   at require (internal/modules/cjs/helpers.js:88:18)
>   at Object. (/data/chenqi/minio-breakpoint-upload/web_src/minio/node_modules/webpack-dev-server/bin/webpack-dev-server.js:12:17)
>   at Module._compile (internal/modules/cjs/loader.js:1068:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>   at Module.load (internal/modules/cjs/loader.js:933:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:774:14)
>   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/data/chenqi/minio-breakpoint-upload/web_src/minio/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
>   ]
>   }
>   npm ERR! code ELIFECYCLE
>   npm ERR! errno 1
>   npm ERR! minio@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
>   npm ERR! Exit status 1
>   npm ERR!
>   npm ERR! Failed at the minio@1.0.0 dev script.
>   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /home/SENSETIME/chenqi1/.npm/_logs/2022-07-13T02_57_01_662Z-debug.log

原因是应该webpack相关包不对，需要使用webpack-cli3版本：
1.  npm i webpack-cli@3.3 -g
2.  npm install webpack@4.30.0 -g
3. npm install webpack-dev-server@3.11.2 -g

但是执行以后还是不行

**Comment by hanzhc** [comment]
https://blog.csdn.net/sxs7970/article/details/88746939

**Comment by gocpplua** [comment]
> https://blog.csdn.net/sxs7970/article/details/88746939

谢谢
